language: python
  
python:
  - "3.6.8"

services:
  - redis-server
addons:
  postgresql: "9.6"
env:
  - DJANGO_VERSION=2.1.7

before_install:
  - export DJANGO_DB_NAME=travis_ci_test
  - export DJANGO_USERNAME=postgres
  - export DJANGO_PASSWORD=''
  - export SECRET_KEY=7uz9h6wsq
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - python manage.py migrate
  - python manage.py test -v 2

after_success:
  - coveralls
